### ISSUE TITLE
Feature Request: Min/Max

### ISSUE THREAD

**Issue by genericsciencer** [markahix/Basic-Scripts#1]
If you're making these plots for multiple systems, having the varying keys types set based on system-specific minimums and maximums can be confusing. Could you add a way to force the color scale minimum and maximum values?

**Comment by markahix** [comment]
I've updated the Correlation Matrix Decomposition script to include -1.0 and 1.0 as the min/max values for the correlation and anti-correlation plots and also adjusted the range for the flip plots to 0.0-2.0 to account for maximum possible values.

Thanks for the heads up!

MAH
